create table public.asistentes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text null,
  telefono text not null,
  email text not null,
  habilidades text null,
  disponible boolean null default false,
  "cuentaAceptada" boolean null default false,
  user_id uuid null,
  rol text null,
  activo boolean null,
  "solicitudSuspendido" boolean null default false,
  constraint asistentes_pkey primary key (id),
  constraint asistentes_email_key unique (email),
  constraint asistentes_telefono_key unique (telefono),
  constraint asistentes_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;



create table public.declaraciones_responsabilidad (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  asistente_id bigint null,
  nombre text not null,
  dni text not null,
  fecha timestamp without time zone null,
  constraint declaraciones_responsabilidad_pkey primary key (id),
  constraint declaraciones_responsabilidad_dni_key unique (dni),
  constraint declaraciones_responsabilidad_asistente_id_fkey foreign KEY (asistente_id) references asistentes (id)
) TABLESPACE pg_default;


create table public.jornadas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  inicio timestamp without time zone null,
  fin timestamp without time zone null,
  asistente_id bigint null,
  constraint jornadas_pkey primary key (id),
  constraint jornadas_asistente_id_fkey foreign KEY (asistente_id) references asistentes (id)
) TABLESPACE pg_default;



create table public.mensajes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  solicitud_id bigint null,
  contenido text not null,
  tipo text null default 'texto'::text,
  leido boolean null default false,
  constraint mensajes_pkey primary key (id),
  constraint mensajes_solicitud_id_fkey foreign KEY (solicitud_id) references solicitudes_asistencia (id)
) TABLESPACE pg_default;





create table public.solicitudes_asistencia (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  usuario_id bigint null,
  asistente_id bigint null,
  room_id text null,
  descripcion text null,
  estado text null default 'pendiente'::text,
  atendido_timestamp timestamp without time zone null,
  finalizado_timestamp timestamp without time zone null,
  tipo_asistencia text null default ''::text,
  constraint solicitud_asistencia_pkey primary key (id),
  constraint solicitud_asistencia_usuario_id_fkey foreign KEY (usuario_id) references usuario (id),
  constraint solicitudes_asistencia_asistente_id_fkey foreign KEY (asistente_id) references asistentes (id)
) TABLESPACE pg_default;



create table public.usuario (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email character varying null,
  nombre text null,
  ip text null,
  user_id uuid null,
  id_dispositivo text null,
  fecha_registro text null default ''::text,
  tipo_usuario text null,
  ultimo_acceso text null,
  constraint usuario_pkey primary key (id),
  constraint usuario_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;



